//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraEscritorio.ServicioWebAseguradora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sw.dw.umg.edu/", ConfigurationName="ServicioWebAseguradora.ServicioAseguradora")]
    public interface ServicioAseguradora {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizaResponse obtenerPoliza(AseguradoraEscritorio.ServicioWebAseguradora.obtenerPoliza request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizasResponse obtenerPolizas(AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizas request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedorResponse modificarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedor request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.pagarBoletaResponse pagarBoleta(AseguradoraEscritorio.ServicioWebAseguradora.pagarBoleta request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.crearPolizaResponse crearPoliza(AseguradoraEscritorio.ServicioWebAseguradora.crearPoliza request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedorResponse obtenerProveedor(AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedor request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPolizaResponse obtenerBoletasPoliza(AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPoliza request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedorResponse agregarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedor request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.actualizarPolizaResponse actualizarPoliza(AseguradoraEscritorio.ServicioWebAseguradora.actualizarPoliza request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedoresResponse obtenerProveedores(AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedores request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaPoliza : respuestaBase {
        
        private poliza polizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public poliza poliza {
            get {
                return this.polizaField;
            }
            set {
                this.polizaField = value;
                this.RaisePropertyChanged("poliza");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class poliza : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activaField;
        
        private string apellidosField;
        
        private consultaCobertura[] consultaCoberturasField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private int idField;
        
        private double montoField;
        
        private int noPagosField;
        
        private string noPolizaField;
        
        private string nombresField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("consultaCoberturas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public consultaCobertura[] consultaCoberturas {
            get {
                return this.consultaCoberturasField;
            }
            set {
                this.consultaCoberturasField = value;
                this.RaisePropertyChanged("consultaCoberturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int noPagos {
            get {
                return this.noPagosField;
            }
            set {
                this.noPagosField = value;
                this.RaisePropertyChanged("noPagos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string noPoliza {
            get {
                return this.noPolizaField;
            }
            set {
                this.noPolizaField = value;
                this.RaisePropertyChanged("noPoliza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class consultaCobertura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string autorizacionField;
        
        private System.DateTime fechaConsultaField;
        
        private bool fechaConsultaFieldSpecified;
        
        private int idField;
        
        private string nitProveedorField;
        
        private poliza polizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
                this.RaisePropertyChanged("autorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaConsulta {
            get {
                return this.fechaConsultaField;
            }
            set {
                this.fechaConsultaField = value;
                this.RaisePropertyChanged("fechaConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaConsultaSpecified {
            get {
                return this.fechaConsultaFieldSpecified;
            }
            set {
                this.fechaConsultaFieldSpecified = value;
                this.RaisePropertyChanged("fechaConsultaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nitProveedor {
            get {
                return this.nitProveedorField;
            }
            set {
                this.nitProveedorField = value;
                this.RaisePropertyChanged("nitProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public poliza poliza {
            get {
                return this.polizaField;
            }
            set {
                this.polizaField = value;
                this.RaisePropertyChanged("poliza");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class boleta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioField;
        
        private string codigoField;
        
        private System.DateTime fechaPagoField;
        
        private bool fechaPagoFieldSpecified;
        
        private int idField;
        
        private int mesField;
        
        private string pagadaField;
        
        private poliza polizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
                this.RaisePropertyChanged("anio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("fechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPagoSpecified {
            get {
                return this.fechaPagoFieldSpecified;
            }
            set {
                this.fechaPagoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pagada {
            get {
                return this.pagadaField;
            }
            set {
                this.pagadaField = value;
                this.RaisePropertyChanged("pagada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public poliza poliza {
            get {
                return this.polizaField;
            }
            set {
                this.polizaField = value;
                this.RaisePropertyChanged("poliza");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nitField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListadoProveedores))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListadoBoletas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaBoleta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaProveedor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaListadoPolizas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaPoliza))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public abstract partial class respuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estadoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaListadoProveedores : respuestaBase {
        
        private proveedor[] proveedoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proveedores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public proveedor[] proveedores {
            get {
                return this.proveedoresField;
            }
            set {
                this.proveedoresField = value;
                this.RaisePropertyChanged("proveedores");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaListadoBoletas : respuestaBase {
        
        private boleta[] boletasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boletas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public boleta[] boletas {
            get {
                return this.boletasField;
            }
            set {
                this.boletasField = value;
                this.RaisePropertyChanged("boletas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaBoleta : respuestaBase {
        
        private boleta boletaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public boleta boleta {
            get {
                return this.boletaField;
            }
            set {
                this.boletaField = value;
                this.RaisePropertyChanged("boleta");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaProveedor : respuestaBase {
        
        private proveedor proveedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public proveedor proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
                this.RaisePropertyChanged("proveedor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sw.dw.umg.edu/")]
    public partial class respuestaListadoPolizas : respuestaBase {
        
        private poliza[] polizasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polizas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public poliza[] polizas {
            get {
                return this.polizasField;
            }
            set {
                this.polizasField = value;
                this.RaisePropertyChanged("polizas");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPoliza", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerPoliza {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerPoliza() {
        }
        
        public obtenerPoliza(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPolizaResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerPolizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return;
        
        public obtenerPolizaResponse() {
        }
        
        public obtenerPolizaResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPolizas", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerPolizas {
        
        public obtenerPolizas() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPolizasResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerPolizasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoPolizas @return;
        
        public obtenerPolizasResponse() {
        }
        
        public obtenerPolizasResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoPolizas @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProveedor", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class modificarProveedor {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0;
        
        public modificarProveedor() {
        }
        
        public modificarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProveedorResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class modificarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return;
        
        public modificarProveedorResponse() {
        }
        
        public modificarProveedorResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pagarBoleta", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class pagarBoleta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public pagarBoleta() {
        }
        
        public pagarBoleta(string arg0, int arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pagarBoletaResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class pagarBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaBoleta @return;
        
        public pagarBoletaResponse() {
        }
        
        public pagarBoletaResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaBoleta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPoliza", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class crearPoliza {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0;
        
        public crearPoliza() {
        }
        
        public crearPoliza(AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearPolizaResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class crearPolizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return;
        
        public crearPolizaResponse() {
        }
        
        public crearPolizaResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProveedor", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerProveedor {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerProveedor() {
        }
        
        public obtenerProveedor(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProveedorResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return;
        
        public obtenerProveedorResponse() {
        }
        
        public obtenerProveedorResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBoletasPoliza", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerBoletasPoliza {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public obtenerBoletasPoliza() {
        }
        
        public obtenerBoletasPoliza(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBoletasPolizaResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerBoletasPolizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoBoletas @return;
        
        public obtenerBoletasPolizaResponse() {
        }
        
        public obtenerBoletasPolizaResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoBoletas @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarProveedor", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class agregarProveedor {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0;
        
        public agregarProveedor() {
        }
        
        public agregarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarProveedorResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class agregarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return;
        
        public agregarProveedorResponse() {
        }
        
        public agregarProveedorResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPoliza", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class actualizarPoliza {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0;
        
        public actualizarPoliza() {
        }
        
        public actualizarPoliza(AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPolizaResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class actualizarPolizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return;
        
        public actualizarPolizaResponse() {
        }
        
        public actualizarPolizaResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProveedores", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerProveedores {
        
        public obtenerProveedores() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProveedoresResponse", WrapperNamespace="http://sw.dw.umg.edu/", IsWrapped=true)]
    public partial class obtenerProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sw.dw.umg.edu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoProveedores @return;
        
        public obtenerProveedoresResponse() {
        }
        
        public obtenerProveedoresResponse(AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoProveedores @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioAseguradoraChannel : AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAseguradoraClient : System.ServiceModel.ClientBase<AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora>, AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora {
        
        public ServicioAseguradoraClient() {
        }
        
        public ServicioAseguradoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAseguradoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAseguradoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAseguradoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizaResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.obtenerPoliza(AseguradoraEscritorio.ServicioWebAseguradora.obtenerPoliza request) {
            return base.Channel.obtenerPoliza(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza obtenerPoliza(string arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerPoliza inValue = new AseguradoraEscritorio.ServicioWebAseguradora.obtenerPoliza();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizaResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).obtenerPoliza(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizasResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.obtenerPolizas(AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizas request) {
            return base.Channel.obtenerPolizas(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoPolizas obtenerPolizas() {
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizas inValue = new AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizas();
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerPolizasResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).obtenerPolizas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedorResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.modificarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedor request) {
            return base.Channel.modificarProveedor(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor modificarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedor inValue = new AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedor();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.modificarProveedorResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).modificarProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.pagarBoletaResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.pagarBoleta(AseguradoraEscritorio.ServicioWebAseguradora.pagarBoleta request) {
            return base.Channel.pagarBoleta(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaBoleta pagarBoleta(string arg0, int arg1, int arg2) {
            AseguradoraEscritorio.ServicioWebAseguradora.pagarBoleta inValue = new AseguradoraEscritorio.ServicioWebAseguradora.pagarBoleta();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            AseguradoraEscritorio.ServicioWebAseguradora.pagarBoletaResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).pagarBoleta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.crearPolizaResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.crearPoliza(AseguradoraEscritorio.ServicioWebAseguradora.crearPoliza request) {
            return base.Channel.crearPoliza(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza crearPoliza(AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.crearPoliza inValue = new AseguradoraEscritorio.ServicioWebAseguradora.crearPoliza();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.crearPolizaResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).crearPoliza(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedorResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.obtenerProveedor(AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedor request) {
            return base.Channel.obtenerProveedor(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor obtenerProveedor(string arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedor inValue = new AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedor();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedorResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).obtenerProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPolizaResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.obtenerBoletasPoliza(AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPoliza request) {
            return base.Channel.obtenerBoletasPoliza(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoBoletas obtenerBoletasPoliza(string arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPoliza inValue = new AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPoliza();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerBoletasPolizaResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).obtenerBoletasPoliza(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedorResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.agregarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedor request) {
            return base.Channel.agregarProveedor(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaProveedor agregarProveedor(AseguradoraEscritorio.ServicioWebAseguradora.proveedor arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedor inValue = new AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedor();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.agregarProveedorResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).agregarProveedor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.actualizarPolizaResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.actualizarPoliza(AseguradoraEscritorio.ServicioWebAseguradora.actualizarPoliza request) {
            return base.Channel.actualizarPoliza(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaPoliza actualizarPoliza(AseguradoraEscritorio.ServicioWebAseguradora.poliza arg0) {
            AseguradoraEscritorio.ServicioWebAseguradora.actualizarPoliza inValue = new AseguradoraEscritorio.ServicioWebAseguradora.actualizarPoliza();
            inValue.arg0 = arg0;
            AseguradoraEscritorio.ServicioWebAseguradora.actualizarPolizaResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).actualizarPoliza(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedoresResponse AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora.obtenerProveedores(AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedores request) {
            return base.Channel.obtenerProveedores(request);
        }
        
        public AseguradoraEscritorio.ServicioWebAseguradora.respuestaListadoProveedores obtenerProveedores() {
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedores inValue = new AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedores();
            AseguradoraEscritorio.ServicioWebAseguradora.obtenerProveedoresResponse retVal = ((AseguradoraEscritorio.ServicioWebAseguradora.ServicioAseguradora)(this)).obtenerProveedores(inValue);
            return retVal.@return;
        }
    }
}
